version: '3.9'

services:
  webapp:
    container_name: ServiceApi
    image: ${DOCKER_REGISTRY-}serviceapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
